### ISSUE TITLE
Displaying notifications causes ActiveRecord::Attribute error

### ISSUE THREAD

**Issue by kbrock** [ManageIQ/manageiq-schema#491]
We just upgraded rails and the ActiveRecord::Attribute model moved over to `ActiveModel::Attribute`.

We are storing some of these records in the database and this is causing issues.

```
FATAL -- : Error caught: [ArgumentError] undefined class/module ActiveRecord::Attribute::

app/models/notification.rb:101:in `text_bindings_dynamic'
app/models/notification.rb:84:in `text_bindings'
app/models/notification.rb:41:in `to_h'
app/models/notification_recipient.rb:10:in `details'
```

Notification#options for the field contains:

```yaml
 :subject: !ruby/object:ManageIQ::Providers::Openstack::CloudManager::CloudVolume
   raw_attributes:
     ems_id: 5
     cloud_tenant_id: 2
     ems_ref: 2b0993c0-d1fe-4e08-b65d-9cbec9047cf1
     id: 102
     type: ManageIQ::Providers::Openstack::CloudManager::CloudVolume
     size: 10737418240
     availability_zone_id: 1
     cloud_volume_snapshot_id:
     name: voltwo
     status: available
     description:
     volume_type:
     bootable: false
     creation_time: '2017-11-08 02:33:11'
     iops:
     encrypted:
     href_slug:
     region_number:
     region_description:
   attributes: !ruby/object:ActiveRecord::AttributeSet
     attributes: !ruby/object:ActiveRecord::LazyAttributeHash
       delegate_hash:
         ems_id: !ruby/object:ActiveRecord::Attribute::FromDatabase
           name: ems_id
           value_before_type_cast: 5
           type: &1 !ruby/object:ActiveModel::Type::Integer
             precision:
```

Our previous fix was:  https://github.com/ManageIQ/manageiq-schema/pull/390

We need to create a similar schema migration to remove or fix these records
